Repository dfinity/nns-dapp, pull requests merged in 2023-05, with the labels that each got.

#2407 Remove symbol estimation ≈ for ckBTC amounts
  frontend/src/lib/components/transaction/TransactionReceivedTokenAmount.svelte
  frontend/src/lib/utils/bitcoin.utils.ts
  frontend/src/tests/lib/components/transaction/TransactionReceivedTokenAmount.spec.ts
  frontend/src/tests/lib/utils/bitcoin.utils.spec.ts
Labels: feature request

#2408 Remove "Typically 12 transactions" static info
  frontend/src/lib/components/accounts/BitcoinTransactionInfo.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/accounts/BitcoinTransactionInfo.spec.ts
Labels: feature request

#2422 Extend getIcrcAccount with owner and subaccount
  frontend/src/lib/api/ckbtc-ledger.api.ts
  frontend/src/lib/api/icrc-ledger.api.ts
  frontend/src/lib/api/sns-ledger.api.ts
  frontend/src/tests/lib/api/icrc-ledger.api.spec.ts
Labels: feature request

#2411 Display Utxo error as success instead of info
  frontend/src/lib/services/ckbtc-minter.services.ts
  frontend/src/lib/types/ckbtc.errors.ts
  frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
Labels: feature request

#2409 Shorten estimated fees label
  frontend/src/lib/i18n/en.json
Labels: feature request

#2412 "Finish" on ckBTC receive modal if BTC is selected should not call update balance
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/tests/lib/components/accounts/CkBTCAccountsFooter.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
Labels: feature request

#2413 Update ckBTC balance success msg
  frontend/src/lib/i18n/en.json
Labels: feature request

#2410 Display detailed balance on ckBTC wallet page
  frontend/src/lib/components/accounts/WalletSummary.svelte
  frontend/src/lib/pages/CkBTCWallet.svelte
  frontend/src/tests/lib/components/accounts/WalletSummary.spec.ts
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
Labels: feature request

#2414 Update ckBTC local deployment doc and commit
  HACKING.md
  scripts/ckbtc/deploy-ckbtc
  scripts/ckbtc/download-ckbtc
Labels: documentation

#2416 Transaction review vertical align
  frontend/src/lib/components/accounts/BitcoinFeeDisplay.svelte
  frontend/src/lib/components/transaction/TransactionReceivedTokenAmount.svelte
  frontend/src/lib/components/transaction/TransactionSource.svelte
  frontend/src/lib/components/transaction/TransactionSummary.svelte
Labels: style

#2418 Display a warning if ckBTC to BTC conversion unexpectedly failed
  frontend/package-lock.json
  frontend/src/lib/components/warnings/ConvertCkBTCToBtcWarning.svelte
  frontend/src/lib/components/warnings/TransactionRateWarning.svelte
  frontend/src/lib/components/warnings/Warnings.svelte
  frontend/src/lib/constants/stores.constants.ts
  frontend/src/lib/i18n/en.json
  frontend/src/lib/services/ckbtc-convert.services.ts
  frontend/src/lib/stores/bitcoin.store.ts
  frontend/src/lib/stores/writable-stored.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/routes/(app)/+layout.svelte
  frontend/src/tests/lib/components/warnings/Warnings.spec.ts
  frontend/src/tests/lib/components/warnings/WarningsTest.svelte
  frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
  frontend/src/tests/lib/stores/bitcoin.store.spec.ts
Labels: feature request

#2428 Fix/proposal not found after voting error
  frontend/src/lib/services/nns-vote-registration.services.ts
Labels: bug

#2430 Check ckBTC minter balance and display call to action
  frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/pages/CkBTCAccounts.svelte
  frontend/src/lib/services/ckbtc-accounts-loader.services.ts
  frontend/src/lib/services/ckbtc-withdrawal-accounts.services.ts
  frontend/src/lib/stores/ckbtc-withdrawal-accounts.store.ts
  frontend/src/lib/stores/icrc-accounts.store.ts
  frontend/src/lib/types/account.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/accounts/CkBTCWithdrawalAccount.spec.ts
  frontend/src/tests/lib/services/ckbtc-accounts-loader.services.spec.ts
  frontend/src/tests/lib/services/ckbtc-accounts.services.spec.ts
  frontend/src/tests/lib/services/ckbtc-withdrawal-accounts.services.spec.ts
  frontend/src/tests/lib/stores/ckbtc-withdrawal-accounts.store.spec.ts
  frontend/src/tests/mocks/ckbtc-accounts.mock.ts
Labels: feature request

#2440 Add option to select destination address methods
  frontend/src/lib/components/accounts/SelectDestinationAddress.svelte
  frontend/src/lib/components/transaction/TransactionForm.svelte
  frontend/src/lib/modals/transaction/TransactionModal.svelte
  frontend/src/lib/types/transaction.ts
  frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts
Labels: feature request

#2441 Display ckBTC withdrawal account and animation
  frontend/package-lock.json
  frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte
  frontend/src/lib/components/accounts/NnsAddAccount.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/accounts/CkBTCWithdrawalAccount.spec.ts
Labels: feature request

#2443 Option to hide ledger fee in transaction
  frontend/src/lib/components/transaction/TransactionForm.svelte
  frontend/src/lib/components/transaction/TransactionFormFee.svelte
  frontend/src/lib/components/transaction/TransactionReview.svelte
  frontend/src/lib/components/transaction/TransactionSummary.svelte
  frontend/src/lib/modals/transaction/TransactionModal.svelte
  frontend/src/lib/types/transaction.ts
  frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
Labels: feature request

#2449 Transaction with withdrawal account
  frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte
  frontend/src/lib/components/transaction/TransactionFormItemNetwork.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/tests/lib/components/accounts/CkBTCWithdrawalAccount.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
Labels: feature request

#2454 Convert ckBTC to BTC for withdrawal account
  frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte
  frontend/src/lib/components/accounts/ConvertBtcInProgress.svelte
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/services/ckbtc-convert.services.ts
  frontend/src/tests/lib/components/accounts/ConvertBtcInProgress.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
  frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
Labels: feature request

#2456 No reload of the transactions for withdrawal account
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/services/ckbtc-accounts-loader.services.ts
  frontend/src/lib/services/ckbtc-convert.services.ts
  frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
Labels: bug

#2459 Improve performance by not necessary getting the withdrawal account again
  frontend/src/lib/services/ckbtc-convert.services.ts
  frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
Labels: feature request

#2466 Height decimals on transaction review
  frontend/package-lock.json
  frontend/src/lib/components/accounts/BitcoinEstimatedFee.svelte
  frontend/src/lib/components/accounts/BitcoinFeeDisplay.svelte
  frontend/src/lib/components/accounts/BitcoinKYTFee.svelte
  frontend/src/lib/components/ic/AmountDisplay.svelte
  frontend/src/lib/components/transaction/TransactionFormFee.svelte
  frontend/src/lib/components/transaction/TransactionReceivedTokenAmount.svelte
  frontend/src/lib/components/transaction/TransactionSource.svelte
  frontend/src/lib/components/transaction/TransactionSummary.svelte
  frontend/src/lib/constants/icp.constants.ts
  frontend/src/lib/utils/token.utils.ts
  frontend/src/tests/lib/components/accounts/BitcoinEstimatedAmountReceived.spec.ts
  frontend/src/tests/lib/components/transaction/TransactionReceivedAmount.spec.ts
  frontend/src/tests/lib/components/transaction/TransactionReceivedTokenAmount.spec.ts
  frontend/src/tests/lib/components/transaction/TransactionSource.spec.ts
  frontend/src/tests/lib/components/transaction/TransactionSummary.spec.ts
  frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
  frontend/src/tests/lib/utils/token.utils.spec.ts
Labels: feature request

#2468 Do not display bitcoin explorer link
  frontend/src/lib/components/accounts/BitcoinAddress.svelte
Labels: bug

#2477 A canister explorer type
  frontend/src/lib/i18n/en.json
Labels: feature request

#2480 feat: btc and kyt fees should not be considered for minimal input amount
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/utils/ckbtc.utils.ts
  frontend/src/tests/lib/utils/ckbtc.utils.spec.ts
Labels: feature request

#2481 Estimated BTC and inter-network fees height decimals
  frontend/src/lib/constants/bitcoin.constants.ts
  frontend/src/lib/utils/bitcoin.utils.ts
  frontend/src/tests/lib/utils/bitcoin.utils.spec.ts
Labels: bug

#2484 Simplify estimated text
  frontend/src/lib/i18n/en.json
Labels: feature request

#2483 Load next transactions after refresh balance
  frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte
  frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
Labels: bug

#2479 ckBTC max input should not reduce ledger fee
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
Labels: bug

#2461 Enable conversion of ckBTC from / to BTC
  frontend/src/lib/components/accounts/BitcoinAddress.svelte
  frontend/src/lib/components/accounts/CkBTCReceiveButton.svelte
  frontend/src/lib/components/accounts/CkBTCWalletActions.svelte
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/pages/CkBTCAccounts.svelte
  frontend/src/lib/services/ckbtc-minter.services.ts
  frontend/src/lib/types/ckbtc-accounts.modal.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
  frontend/src/tests/lib/pages/CkBTCAccounts.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
Labels: feature request

#2471 WiP Update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  frontend/package-lock.json
  frontend/package.json
Labels: release

#2487 Reload all ckBTC transactions after update balance
  frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte
  frontend/src/lib/stores/icrc-transactions.store.ts
  frontend/src/lib/utils/icrc-transactions.utils.ts
  frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCTransactionsListTest.svelte
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
  frontend/src/tests/lib/routes/Wallet.spec.ts
  frontend/src/tests/lib/stores/icrc-transactions.store.spec.ts
Labels: feature request

#2473 fix: reload proposals on sns switch
  frontend/src/lib/pages/SnsProposals.svelte
Labels: bug

#2509 feat: maturityLastDistribution util
  frontend/src/lib/components/neuron-detail/NnsNeuronMaturityCard.svelte
  frontend/src/lib/utils/neuron.utils.ts
  frontend/src/tests/lib/components/neuron-detail/NnsNeuronMaturityCard.spec.ts
  frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
  frontend/src/tests/lib/utils/neuron.utils.spec.ts
Labels: bug

#2510 ckBTC refresh balance link in explanation paragraph
  frontend/src/lib/components/accounts/BitcoinAddress.svelte
  frontend/src/lib/components/accounts/CkBTCWalletActions.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/pages/CkBTCWallet.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/accounts/BitcoinAddress.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCWalletActions.spec.ts
Labels: feature request

#2507 Changelog update
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  frontend/package-lock.json
  frontend/package.json
Labels: release

#2534 changelog update
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  frontend/package-lock.json
  frontend/package.json
Labels: release

#2537 Update changelog
  CHANGELOG.md
Labels: release

#2566 Style test banner
  frontend/src/lib/components/header/Banner.svelte
Labels: style

#2568 Fix e2e tsconfig exclude
  frontend/src/tests/e2e/sns-participation.spec.ts
  frontend/src/tests/e2e/tsconfig.json
Labels: build

#2567 Script to test reproducibility locally
  frontend/scripts/test-reproducibility
Labels: build

#2562 Lazy load ledger and qr-code chunks
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/identities/ledger.identity.ts
  frontend/src/lib/utils/ledger.utils.ts
  frontend/src/tests/lib/utils/ledger.utils.spec.ts
  frontend/vite.config.ts
Labels: build

#2593 Display spinner on navigation after sign-in
  frontend/src/routes/(login)/+layout.svelte
Labels: feature request

#2600 Update (fav)icons
  frontend/src/app.html
  frontend/static/assets/favicons/apple-touch-icon.png
  frontend/static/assets/favicons/browserconfig.xml
  frontend/static/assets/favicons/icon-16x16.png
  frontend/static/assets/favicons/icon-192x192.png
  frontend/static/assets/favicons/icon-32x32.png
  frontend/static/assets/favicons/icon-512x512.png
  frontend/static/assets/favicons/mstile-150x150.png
  frontend/static/assets/favicons/safari-pinned-tab.svg
  frontend/static/favicon.ico
Labels: feature request

#2601 Update title and description
  frontend/src/app.html
  frontend/src/tests/e2e/accounts.spec.ts
  frontend/src/tests/e2e/sns-governance.spec.ts
  frontend/src/tests/e2e/sns-participation.spec.ts
  frontend/static/manifest.json
Labels: feature request

#2581 Update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  frontend/package-lock.json
  frontend/package.json
Labels: release
