Repository dfinity/nns-dapp, pull requests merged in 2023-03, with the labels that each got.

#1998 feat: subnect transaction rate warning
  frontend/jest-setup.ts
  frontend/package-lock.json
  frontend/src/lib/components/canisters/CanisterCardCycles.svelte
  frontend/src/lib/components/common/MenuMetrics.svelte
  frontend/src/lib/components/login/LoginHeader.svelte
  frontend/src/lib/components/metrics/Metrics.svelte
  frontend/src/lib/components/metrics/TotalValueLocked.svelte
  frontend/src/lib/components/metrics/TransactionRateWarning.svelte
  frontend/src/lib/components/metrics/TransactionRateWarningIcon.svelte
  frontend/src/lib/components/metrics/Warnings.svelte
  frontend/src/lib/constants/dashboard.constants.ts
  frontend/src/lib/constants/environment.constants.ts
  frontend/src/lib/constants/metrics.constants.ts
  frontend/src/lib/constants/warnings.constants.ts
  frontend/src/lib/i18n/en.json
  frontend/src/lib/pages/CkBTCWallet.svelte
  frontend/src/lib/pages/SnsWallet.svelte
  frontend/src/lib/rest/dashboard.rest.ts
  frontend/src/lib/stores/toasts.store.ts
  frontend/src/lib/types/binance.ts
  frontend/src/lib/types/dashboard.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/types/metrics.ts
  frontend/src/lib/workers/metrics.worker.ts
  frontend/src/routes/(app)/+layout.svelte
  frontend/src/routes/(login)/+layout.svelte
  frontend/src/tests/lib/components/metrics/TotalValueLocked.spec.ts
  frontend/src/tests/lib/components/metrics/TotalValueLockedTest.svelte
  frontend/src/tests/lib/components/metrics/Warnings.spec.ts
  frontend/src/tests/lib/components/metrics/WarningsTest.svelte
  frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts
  frontend/src/tests/lib/rest/dashboard.rest.spec.ts
  frontend/src/tests/lib/services/neurons.services.spec.ts
Labels: feature request

#1944 fix: derivation origin
  frontend/__mocks__/$app/environment.ts
  frontend/src/lib/constants/environment.constants.ts
  frontend/src/lib/constants/origin.constants.ts
  frontend/src/lib/stores/auth.store.ts
  frontend/src/lib/utils/env.utils.ts
  frontend/src/tests/lib/utils/env.utils.spec.ts
Labels: bug

#1970 build: chunks group workers and api-services
  frontend/vite.config.ts
Labels: build

#1934 build: upgrade sveltekit
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/build.csp.mjs
  frontend/src/app.html
  frontend/src/tests/lib/api/sns-governance.api.spec.ts
  frontend/src/tests/lib/api/sns.api.spec.ts
  frontend/src/tests/lib/components/accounts/HardwareWalletListNeuronsButton.spec.ts
  rs/backend/src/assets.rs
Labels: build

#1959 feat: plug convert ckBTC to BTC in ckBTC transaction modal
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
  frontend/src/tests/utils/transaction-modal.test.utils.ts
Labels: feature request

#1950 feat: bitcoin network estimated fee
  frontend/package-lock.json
  frontend/src/lib/api/ckbtc-minter.api.ts
  frontend/src/lib/components/accounts/BitcoinEstimatedFee.svelte
  frontend/src/lib/components/accounts/BitcoinEstimatedFeeDisplay.svelte
  frontend/src/lib/constants/bitcoin.constants.ts
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/services/ckbtc-minter.services.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/utils/bitcoin.utils.ts
  frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
  frontend/src/tests/lib/components/accounts/BitcoinEstimatedFee.spec.ts
  frontend/src/tests/lib/components/accounts/BitcoinEstimatedFeeDisplay.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
  frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
  frontend/src/tests/lib/stores/toasts.store.spec.ts
  frontend/src/tests/lib/utils/bitcoin.utils.spec.ts
  frontend/src/tests/lib/utils/universes.utils.spec.ts
  scripts/ckbtc/deploy-ckbtc
  scripts/ckbtc/download-ckbtc
Labels: feature request

#2033 bump agent-js to 0.15.4
  frontend/package-lock.json
  frontend/package.json
Labels: build

#2030 feat: validate btc input address
  frontend/src/lib/components/accounts/Address.svelte
  frontend/src/lib/components/accounts/AddressInput.svelte
  frontend/src/lib/components/accounts/BitcoinEstimatedFee.svelte
  frontend/src/lib/components/accounts/SelectDestinationAddress.svelte
  frontend/src/lib/components/accounts/SelectNetworkDropdown.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/types/transaction.ts
  frontend/src/lib/utils/accounts.utils.ts
  frontend/src/lib/utils/transactions.utils.ts
  frontend/src/tests/lib/components/accounts/AddressInput.spec.ts
  frontend/src/tests/lib/components/accounts/BitcoinEstimatedFee.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
  frontend/src/tests/lib/components/accounts/SelectNetworkDropdown.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
  frontend/src/tests/lib/utils/accounts.utils.spec.ts
  frontend/src/tests/lib/utils/transactions.utils.spec.ts
  frontend/src/tests/utils/transaction-modal.test.utils.ts
Labels: feature request

#2039 feat: ICP and Sns receive modal with QR-Code
  frontend/jest-setup.ts
  frontend/src/lib/assets/icp-rounded.svg
  frontend/src/lib/assets/icp.svg
  frontend/src/lib/components/accounts/CkBTCWalletFooter.svelte
  frontend/src/lib/components/accounts/ReceiveAddressQRCode.svelte
  frontend/src/lib/components/universe/UniverseLogo.svelte
  frontend/src/lib/constants/environment.constants.ts
  frontend/src/lib/constants/icp.constants.ts
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/lib/modals/accounts/CkBTCWalletModals.svelte
  frontend/src/lib/modals/accounts/ReceiveModal.svelte
  frontend/src/lib/pages/NnsWallet.svelte
  frontend/src/lib/pages/SnsWallet.svelte
  frontend/src/lib/stores/busy.store.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/types/wallet.modal.ts
  frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
  frontend/src/tests/lib/components/summary/SummaryLogo.spec.ts
  frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
  frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
  frontend/src/tests/lib/pages/NnsWallet.spec.ts
  frontend/src/tests/lib/pages/SnsWallet.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/mocks/modal.mock.ts
  frontend/static/assets/100_on_chain-small-centered-white_text.svg
Labels: feature request

#2049 feat: select network automatically
  frontend/src/lib/components/accounts/SelectNetworkDropdown.svelte
  frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
  frontend/src/lib/utils/accounts.utils.ts
  frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
  frontend/src/tests/lib/components/accounts/AddressInput.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
  frontend/src/tests/lib/components/accounts/SelectNetworkDropdown.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
  frontend/src/tests/lib/pages/SnsWallet.spec.ts
  frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
  frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
  frontend/src/tests/lib/utils/accounts.utils.spec.ts
  frontend/src/tests/mocks/ckbtc-accounts.mock.ts
Labels: feature request

#2085 fix: display IC on canisters view
  frontend/src/lib/components/summary/Summary.svelte
  frontend/src/tests/lib/components/summary/Summary.spec.ts
Labels: bug

#2083 feat: display ckBTC to BTC estimated time
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
Labels: feature request

#2092 feat: read destination address with an integrated QR code reader
  frontend/package-lock.json
  frontend/src/lib/components/accounts/AddressInput.svelte
  frontend/src/lib/components/accounts/NnsAddress.svelte
  frontend/src/lib/components/accounts/SelectDestinationAddress.svelte
  frontend/src/lib/components/ui/Input.svelte
  frontend/src/lib/components/ui/InputWithError.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
  frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
  frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
  frontend/src/lib/modals/accounts/NewTransaction/TransactionQRCode.svelte
  frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/accounts/AddressInput.spec.ts
  frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts
Labels: feature request

#2101 feat: add account button card
  frontend/package-lock.json
  frontend/src/lib/components/accounts/AddAccountType.svelte
  frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
  frontend/src/lib/components/accounts/NnsAddAccount.svelte
  frontend/src/lib/pages/NnsAccounts.svelte
  frontend/src/lib/themes/legacy.scss
Labels: feature request

#2105 feat: add "Receive" modal on every "Accounts" view
  frontend/src/app.d.ts
  frontend/src/lib/components/accounts/CkBTCAccountsFooter.svelte
  frontend/src/lib/components/accounts/CkBTCReceiveButton.svelte
  frontend/src/lib/components/accounts/CkBTCSendButton.svelte
  frontend/src/lib/components/accounts/CkBTCWalletFooter.svelte
  frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
  frontend/src/lib/components/accounts/ReceiveAddressQRCode.svelte
  frontend/src/lib/components/accounts/ReceiveButton.svelte
  frontend/src/lib/components/accounts/ReceiveSelectAccountDropdown.svelte
  frontend/src/lib/components/accounts/SnsAccountsFooter.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/AccountsModals.svelte
  frontend/src/lib/modals/accounts/CkBTCAccountsModals.svelte
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/lib/modals/accounts/CkBTCTransactionTokenModal.svelte
  frontend/src/lib/modals/accounts/CkBTCWalletModals.svelte
  frontend/src/lib/modals/accounts/NnsReceiveModal.svelte
  frontend/src/lib/modals/accounts/ReceiveModal.svelte
  frontend/src/lib/modals/accounts/SnsReceiveModal.svelte
  frontend/src/lib/pages/CkBTCWallet.svelte
  frontend/src/lib/pages/NnsWallet.svelte
  frontend/src/lib/pages/SnsWallet.svelte
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/lib/routes/Wallet.svelte
  frontend/src/lib/types/accounts.modal.ts
  frontend/src/lib/types/ckbtc-accounts.modal.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/types/wallet.modal.ts
  frontend/src/lib/utils/modals.utils.ts
  frontend/src/tests/lib/components/accounts/CkBTCAccountsFooter.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCAccountsTest.svelte
  frontend/src/tests/lib/components/accounts/CkBTCWalletContextTest.svelte
  frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
  frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
  frontend/src/tests/lib/pages/AccountsTest.svelte
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
  frontend/src/tests/lib/pages/NnsWallet.spec.ts
  frontend/src/tests/lib/pages/SnsWallet.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
Labels: feature request

#2125 feat: receive modal text
  frontend/package-lock.json
  frontend/src/lib/components/accounts/ReceiveAddressQRCode.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/lib/modals/accounts/NnsReceiveModal.svelte
  frontend/src/lib/modals/accounts/ReceiveModal.svelte
  frontend/src/lib/modals/accounts/SnsReceiveModal.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
  frontend/src/tests/lib/pages/NnsWallet.spec.ts
  frontend/src/tests/lib/pages/SnsWallet.spec.ts
Labels: feature request

#2141 feat: make ckBTC default segment of receive modal with Bitcoin
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
Labels: feature request

#2139 feat: reload accounts on "Finish" action of "Receive" modal
  frontend/src/lib/components/accounts/CkBTCAccountsFooter.svelte
  frontend/src/lib/components/accounts/CkBTCReceiveButton.svelte
  frontend/src/lib/components/accounts/CkBTCWalletFooter.svelte
  frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
  frontend/src/lib/components/accounts/ReceiveButton.svelte
  frontend/src/lib/components/accounts/SnsAccountsFooter.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/lib/modals/accounts/NnsReceiveModal.svelte
  frontend/src/lib/modals/accounts/ReceiveModal.svelte
  frontend/src/lib/modals/accounts/SnsReceiveModal.svelte
  frontend/src/lib/pages/NnsWallet.svelte
  frontend/src/lib/pages/SnsWallet.svelte
  frontend/src/lib/types/accounts.modal.ts
  frontend/src/lib/types/ckbtc-accounts.modal.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/accounts/CkBTCAccountsFooter.spec.ts
  frontend/src/tests/lib/components/accounts/NnsAccountsFooter.spec.ts
  frontend/src/tests/lib/components/accounts/SnsAccountsFooter.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
  frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
  frontend/src/tests/lib/pages/NnsWallet.spec.ts
  frontend/src/tests/lib/pages/SnsWallet.spec.ts
  frontend/src/tests/utils/accounts.test-utils.ts
Labels: feature request

#2150 fix: qr code reader
  frontend/package-lock.json
  frontend/src/lib/components/accounts/ReceiveAddressQRCode.svelte
  frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
Labels: bug

#2161 fix: "estimated amount received BTC" should not be displayed for ckBTC network
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
Labels: bug

#2164 feat: do not display token symbol in labels of transactions list
  frontend/src/lib/i18n/en.json
  frontend/src/lib/utils/transactions.utils.ts
Labels: feature request

#2163 feat: display Bitcoin Testnet in receive modal for ckTESTBTC
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/summary/SummaryLogo.spec.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
  frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
Labels: feature request

#2162 feat: redo no update balance on ckBTC close
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
Labels: feature request

#2158 fix: settings back
  frontend/src/routes/(app)/(nns)/settings/+layout.svelte
Labels: bug

#2165 feat: get BTC address once Receive modal displayed
  frontend/src/lib/components/accounts/CkBTCReceiveButton.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
  frontend/src/lib/stores/busy.store.ts
  frontend/src/lib/types/ckbtc-accounts.modal.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
Labels: feature request

#2214 fix: settings title and visual quirks
  frontend/src/lib/routes/Settings.svelte
  frontend/src/lib/themes/global.scss
  frontend/src/tests/lib/routes/Settings.spec.ts
Labels: bug
