Repository dfinity/nns-dapp, pull requests merged in 2023-11, with the labels that each got.

#3646 Bump gix-cmp to v3.1.0
  frontend/package-lock.json
Labels: build

#3656 Beautify proposal cards and fix hidden missing Sns proposer id
  CHANGELOG-Nns-Dapp-unreleased.md
  frontend/package-lock.json
  frontend/src/lib/components/proposals/NnsProposalCard.svelte
  frontend/src/lib/components/proposals/ProposalCard.svelte
  frontend/src/lib/components/sns-proposals/SnsProposalCard.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/proposals/ProposalCard.spec.ts
  frontend/src/tests/lib/components/sns-proposals/SnsProposalCard.spec.ts
  frontend/src/tests/page-objects/ProposalCard.page-object.ts
Labels: feature request

#3688 Fix: Canister title when not controller
  CHANGELOG-Nns-Dapp-unreleased.md
  frontend/src/lib/canisters/ic-management/ic-management.errors.ts
  frontend/src/tests/lib/canisters/ic-management.canister.spec.ts
  frontend/src/tests/lib/canisters/ic-management.errors.spec.ts
Labels: Unplanned

#3690 Add balance not available TokensTable
  frontend/src/lib/components/tokens/DesktopTokensTable/DesktopTokensTableRow.svelte
  frontend/src/lib/types/tokens-page.ts
  frontend/src/lib/utils/token.utils.ts
  frontend/src/routes/(app)/(nns)/tokens/+page.svelte
  frontend/src/tests/lib/components/tokens/DesktopTokensTable.spec.ts
Labels: Planned

#3710 GIX-1979: Load ckBTC tokens
  frontend/src/lib/services/ckbtc-tokens.services.ts
  frontend/src/tests/lib/services/ckbtc-tokens.services.spec.ts
Labels: Planned

#3711 GIX-1979: Move universesStore
  frontend/src/lib/components/canister-detail/CanisterPageHeader.svelte
  frontend/src/lib/components/neuron-detail/NnsNeuronPageHeader.svelte
  frontend/src/lib/components/neuron-detail/NnsStakeItemAction.svelte
  frontend/src/lib/components/summary/Summary.svelte
  frontend/src/lib/components/summary/SummaryLogo.svelte
  frontend/src/lib/constants/universes.constants.ts
  frontend/src/lib/derived/selectable-universes.derived.ts
  frontend/src/lib/derived/selected-universe.derived.ts
  frontend/src/lib/derived/universes.derived.ts
  frontend/src/lib/pages/NnsWallet.svelte
  frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
  frontend/src/tests/lib/components/universe/UniverseAccountsBalance.spec.ts
  frontend/src/tests/lib/components/universe/UniverseName.spec.ts
  frontend/src/tests/lib/components/universe/UniversePageSummary.spec.ts
  frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
  frontend/src/tests/lib/derived/universes.derived.spec.ts
Labels: Planned

#3739 GIX-1979: Render table visitors
  frontend/src/lib/components/tokens/DesktopTokensTable/DesktopTokensTableRow.svelte
  frontend/src/lib/pages/SignInTokens.svelte
  frontend/src/routes/(app)/(nns)/tokens/+page.svelte
  frontend/src/tests/page-objects/DesktopTokensTableRow.page-object.ts
  frontend/src/tests/page-objects/SignInTokens.page-object.ts
  frontend/src/tests/page-objects/TokensRoute.page-object.ts
  frontend/src/tests/routes/app/tokens/page.spec.ts
Labels: Planned

#3740 Feat: Add logo and title to Universe
  frontend/src/lib/components/canister-detail/CanisterPageHeader.svelte
  frontend/src/lib/components/neuron-detail/NnsNeuronPageHeader.svelte
  frontend/src/lib/components/neuron-detail/NnsStakeItemAction.svelte
  frontend/src/lib/components/summary/Summary.svelte
  frontend/src/lib/components/summary/SummaryLogo.svelte
  frontend/src/lib/constants/universes.constants.ts
  frontend/src/lib/derived/ckbtc-universe.derived.ts
  frontend/src/lib/derived/ckbtc-universes.derived.ts
  frontend/src/lib/derived/cktestbtc-universe.derived.ts
  frontend/src/lib/derived/nns-universe.derived.ts
  frontend/src/lib/derived/selected-universe.derived.ts
  frontend/src/lib/derived/universes.derived.ts
  frontend/src/lib/pages/NnsWallet.svelte
  frontend/src/lib/types/universe.ts
  frontend/src/lib/utils/sns-aggregator-converters.utils.ts
  frontend/src/lib/utils/universe.utils.ts
  frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
  frontend/src/tests/lib/components/universe/SelectUniverseList.spec.ts
  frontend/src/tests/lib/components/universe/UniverseAccountsBalance.spec.ts
  frontend/src/tests/lib/components/universe/UniverseName.spec.ts
  frontend/src/tests/lib/components/universe/UniversePageSummary.spec.ts
  frontend/src/tests/lib/derived/ckbtc-universe.derived.spec.ts
  frontend/src/tests/lib/derived/cktestbtc-universe.derived.spec.ts
  frontend/src/tests/lib/derived/nns-universe.derived.spec.ts
  frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
  frontend/src/tests/lib/derived/universes.derived.spec.ts
  frontend/src/tests/lib/utils/universes.utils.spec.ts
  frontend/src/tests/mocks/sns-projects.mock.ts
  frontend/src/tests/mocks/universe.mock.ts
Labels: Planned

#3743 GIX-1979: Render ckBTC token
  frontend/src/routes/(app)/(nns)/tokens/+page.svelte
  frontend/src/tests/routes/app/tokens/page.spec.ts
Labels: Planned

#3753 Fix_debug-store
  CHANGELOG-Nns-Dapp-unreleased.md
  frontend/src/lib/derived/debug.derived.ts
Labels: Unplanned

#3752 Rename DesktopTokensTable
  frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
  frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
  frontend/src/lib/components/tokens/TokensTable/actions/GoToDetailButton.svelte
  frontend/src/lib/components/tokens/TokensTable/actions/ReceiveButton.svelte
  frontend/src/lib/components/tokens/TokensTable/actions/SendButton.svelte
  frontend/src/lib/pages/SignInTokens.svelte
  frontend/src/lib/pages/Tokens.svelte
  frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
  frontend/src/tests/page-objects/DesktopTokensTable.page-object.ts
  frontend/src/tests/page-objects/SignInTokens.page-object.ts
  frontend/src/tests/page-objects/TokensPage.page-object.ts
  frontend/src/tests/page-objects/TokensTable.page-object.ts
  frontend/src/tests/page-objects/TokensTableRow.page-object.ts
Labels: Planned

#3759 Fix: Adapt tokens table border radius
  frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
Labels: Planned

#3750 GIX-1979: Login action visitors
  frontend/src/lib/derived/tokens-list-visitors.derived.ts
  frontend/src/lib/pages/SignInTokens.svelte
  frontend/src/routes/(app)/(nns)/tokens/+page.svelte
  frontend/src/tests/lib/derived/tokens-list-visitors.derived.spec.ts
  frontend/src/tests/routes/app/tokens/page.spec.ts
Labels: Planned

#3767 GIX-2005_LM_fix-tablet-horizontal-spacing
  frontend/src/lib/components/tokens/MainWrapper.svelte
Labels: Planned

#3776 GIX-2082: Add subtitle to TokensTable
  frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
  frontend/src/lib/types/tokens-page.ts
  frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
  frontend/src/tests/page-objects/TokensTableRow.page-object.ts
Labels: Planned

#3775 GIX-1980: Setup icp accounts with tokens table
  frontend/src/lib/pages/NnsAccounts.svelte
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/tests/lib/pages/NnsAccounts.spec.ts
  frontend/src/tests/page-objects/NnsAccounts.page-object.ts
  frontend/src/tests/routes/app/accounts/page.spec.ts
Labels: Planned

#3784 Fix: SignIn Tokens width page
  frontend/src/lib/components/tokens/MainWrapper.svelte
  frontend/src/lib/pages/SignInTokens.svelte
  frontend/src/lib/pages/Tokens.svelte
  frontend/src/routes/(app)/(nns)/tokens/+layout.svelte
Labels: Planned

#3800 Chore: Remove unnecessary class
  frontend/src/lib/pages/SignInAccounts.svelte
  frontend/src/lib/pages/SignInCanisters.svelte
  frontend/src/lib/pages/SignInNeurons.svelte
  frontend/src/lib/pages/SignInSettings.svelte
  frontend/src/lib/themes/global.scss
Labels: Planned

#3807 GIX-2058: Derived store ICP Tokens visitor
  frontend/src/lib/derived/icp-tokens-list-visitors.derived.ts
  frontend/src/tests/lib/derived/icp-tokens-list-visitors.derived.spec.ts
Labels: Planned

#3802 Chore: Upgrade next dependencies
  frontend/package-lock.json
  frontend/src/lib/api/icrc-ledger.api.ts
  frontend/src/lib/api/sns-governance.api.ts
  frontend/src/lib/services/sns-neurons-check-balances.services.ts
  frontend/src/lib/types/sns.ts
  frontend/src/lib/types/transaction.ts
  frontend/src/lib/utils/accounts.utils.ts
  frontend/src/lib/utils/icrc-transactions.utils.ts
  frontend/src/lib/utils/sns-neuron.utils.ts
  frontend/src/tests/fakes/sns-governance-api.fake.ts
  frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
  frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Labels: Planned

#3806 GIX-2085: AccountsPlusPagePo
  frontend/src/routes/(app)/(u)/(accounts)/+page.svelte
  frontend/src/routes/(app)/(u)/(accounts)/accounts/+page.svelte
  frontend/src/tests/page-objects/AccountsPlusPage.page-object.ts
  frontend/src/tests/routes/app/accounts/page.spec.ts
Labels: Planned

#3812 GIX-2089: Update Send icon
  frontend/src/lib/components/tokens/TokensTable/actions/SendButton.svelte
Labels: Planned

#3810 GIX-2085: Use TokensTable in SignInAccounts
  frontend/src/lib/components/common/EmptyCards.svelte
  frontend/src/lib/pages/NnsAccounts.svelte
  frontend/src/lib/pages/SignInAccounts.svelte
  frontend/src/routes/(app)/(u)/(accounts)/+layout.svelte
  frontend/src/routes/(app)/(u)/(accounts)/+page.svelte
  frontend/src/routes/(app)/(u)/(accounts)/accounts/+page.svelte
  frontend/src/tests/page-objects/AccountsPlusPage.page-object.ts
  frontend/src/tests/page-objects/SignInAccounts.page-object.ts
  frontend/src/tests/routes/app/accounts/layout.spec.ts
  frontend/src/tests/routes/app/accounts/page.spec.ts
Labels: Planned

#3811 GIX-2058: IcpTokensListUser derived store
  frontend/src/lib/derived/icp-tokens-list-user.derived.ts
  frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
Labels: Planned

#3818 Chore: Move test to describe
  frontend/src/tests/lib/pages/NnsAccounts.spec.ts
Labels: Planned

#3824 GIX-1983: Add SnsTransaction functionality
  frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
  frontend/src/routes/(app)/(nns)/tokens/+page.svelte
  frontend/src/tests/page-objects/SnsTransactionModal.page-object.ts
  frontend/src/tests/page-objects/TokensPage.page-object.ts
  frontend/src/tests/page-objects/TokensRoute.page-object.ts
  frontend/src/tests/page-objects/TokensTable.page-object.ts
  frontend/src/tests/routes/app/tokens/page.spec.ts
Labels: Planned

#3796 GIX-2094: Buy ICP Modal
  CHANGELOG-Nns-Dapp-unreleased.md
  frontend/src/lib/assets/banxa-logo.svg
  frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
  frontend/src/lib/components/layout/Footer.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/AccountsModals.svelte
  frontend/src/lib/modals/accounts/BuyIcpModal.svelte
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/lib/themes/mixins/_button.scss
  frontend/src/lib/types/accounts.modal.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-1-Google-Chrome-linux.png
  frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-1-firefox-linux.png
  frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-wide-screen-1-Google-Chrome-linux.png
  frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-wide-screen-1-firefox-linux.png
  frontend/src/tests/lib/modals/accounts/BuyIcpModal.spec.ts
  frontend/src/tests/page-objects/Accounts.page-object.ts
  frontend/src/tests/page-objects/BuyICPModal.page-object.ts
  frontend/src/tests/page-objects/NnsAccountsFooter.page-object.ts
  frontend/src/tests/routes/app/accounts/page.spec.ts
Labels: Unplanned

#3827 Chore: Add missing fields to SnsSummarySwap
  frontend/src/lib/types/sns.ts
  frontend/src/lib/utils/sns-aggregator-converters.utils.ts
  frontend/src/tests/mocks/sns-projects.mock.ts
Labels: Planned

#3829 GIX-2102: Remove default firstColumnHeader
  frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
  frontend/src/lib/pages/SignInTokens.svelte
  frontend/src/lib/pages/Tokens.svelte
  frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
  frontend/src/tests/routes/app/tokens/page.spec.ts
Labels: Planned

#3833 Chore: Remove hardcoded text
  frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
Labels: Planned

#3830 GIX-2062: Add loading balance
  frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
  frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
  frontend/src/lib/components/tokens/TokensTable/actions/GoToDetailButton.svelte
  frontend/src/lib/types/tokens-page.ts
  frontend/src/lib/utils/user-token.utils.ts
  frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
  frontend/src/tests/mocks/tokens-page.mock.ts
  frontend/src/tests/page-objects/TokensTableRow.page-object.ts
Labels: Planned

#3825 Refactor: Create SnsSummaryWrapper
  frontend/src/lib/stores/sns.store.ts
  frontend/src/lib/types/sns-summary-wrapper.ts
  frontend/src/lib/utils/sns-aggregator-converters.utils.ts
  frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
Labels: Planned

#3854 GIX-2117: Add ledger api endpoints
  frontend/src/lib/api/icrc-ledger.api.ts
  frontend/src/tests/lib/api/icrc-ledger.api.spec.ts
Labels: Planned

#3861 GIX-2117: Add cketh services
  frontend/src/lib/services/icrc-accounts.services.ts
  frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
Labels: Planned

#3863 GIX-2118: Add ckETH universe derived
  frontend/src/lib/derived/icrc-universes.derived.ts
  frontend/src/tests/lib/derived/icrc-universes.derived.spec.ts
  frontend/src/tests/mocks/cketh-accounts.mock.ts
  frontend/src/tests/mocks/universe.mock.ts
Labels: Planned

#3865 Feat: Add ckETH logos
  frontend/src/lib/assets/ckETH.svg
  frontend/src/lib/assets/ckSepoliaETH.svg
Labels: Planned

#3866 Chore: Rename pathSupportsCkBTC
  frontend/src/lib/derived/selectable-universes.derived.ts
  frontend/src/lib/derived/selected-universe.derived.ts
  frontend/src/lib/utils/universe.utils.ts
  frontend/src/tests/lib/utils/universes.utils.spec.ts
Labels: Planned

#3868 GIX-2117: Load ckETH on Accounts page
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/lib/services/cketh-canisters.services.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/lib/services/cketh-canisters.services.spec.ts
Labels: Planned

#3872 GIX-2121: Add ICRC Token universe selected store
  frontend/src/lib/derived/selected-universe.derived.ts
  frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
Labels: Planned

#3877 Chore: Remove unnecessary expects
  frontend/src/tests/lib/routes/Accounts.spec.ts
Labels: Planned

#3878 GIX-2121: selectedIcrcTokenUniverseIdStore
  frontend/src/lib/derived/selected-universe.derived.ts
  frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
Labels: Planned

#3879 GIX-2121: Setup IcrcTokenAccounts
  frontend/src/lib/pages/IcrcTokenAccounts.svelte
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/page-objects/Accounts.page-object.ts
  frontend/src/tests/page-objects/IcrcTokenAccounts.page-object.ts
Labels: Planned

#3870 GIX-2118: Add ckETH to universesStore
  frontend/src/lib/derived/universes.derived.ts
  frontend/src/tests/lib/derived/universes.derived.spec.ts
Labels: Planned

#3873 Start-snapshot command
  frontend/package.json
Labels: build

#3882 Chore: Add ckETHSEPOLIA index canister id
  frontend/src/lib/constants/cketh-canister-ids.constants.ts
Labels: Planned

#3888 GIX-2123: Setup IcrcTokenAccountsFooter
  frontend/src/lib/components/accounts/IcrcTokenAccountsFooter.svelte
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/page-objects/Accounts.page-object.ts
  frontend/src/tests/page-objects/IcrcTokenAccountsFooter.page-object.ts
Labels: Planned

#3883 GIX-2121: Render accounts in IcrcTokenAccounts
  frontend/src/lib/pages/IcrcTokenAccounts.svelte
  frontend/src/tests/lib/pages/IcrcTokenAccounts.spec.ts
  frontend/src/tests/mocks/icrc-accounts.mock.ts
  frontend/src/tests/page-objects/IcrcTokenAccounts.page-object.ts
Labels: Planned

#3890 GIX-2121: Fix snsOnlyProjectStore
  frontend/src/lib/derived/sns/sns-selected-project.derived.ts
  frontend/src/tests/lib/components/accounts/SnsTransactionsList.spec.ts
  frontend/src/tests/lib/components/accounts/SnsWalletTransactionsObserver.spec.ts
  frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts
  frontend/src/tests/lib/derived/sns/sns-selected-project.derived.spec.ts
  frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
  frontend/src/tests/lib/pages/SnsProposals.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
Labels: Planned

#3894 Extract content from ckBTCWallet & IcrcWallet === ckETH Wallet page
  frontend/src/lib/components/accounts/IcrcWalletPage.svelte
  frontend/src/lib/constants/cketh-canister-ids.constants.ts
  frontend/src/lib/pages/CkBTCWallet.svelte
  frontend/src/lib/pages/IcrcWallet.svelte
  frontend/src/lib/routes/Wallet.svelte
  frontend/src/tests/lib/pages/IcrcWallet.spec.ts
  frontend/src/tests/lib/routes/Wallet.spec.ts
  frontend/src/tests/mocks/cketh-accounts.mock.ts
  frontend/src/tests/mocks/tokens.mock.ts
  frontend/src/tests/page-objects/IcrcWallet.page-object.ts
Labels: feature request

#3900 GIX-2144: Do not request token data if present
  frontend/src/lib/services/icrc-accounts.services.ts
  frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
Labels: Planned

#3897 GIX-2122: Send CkETH Tokens
  frontend/src/app.d.ts
  frontend/src/lib/components/accounts/IcrcTokenAccountsFooter.svelte
  frontend/src/lib/modals/accounts/IcrcTokenAccountsModals.svelte
  frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/lib/services/icrc-accounts.services.ts
  frontend/src/lib/types/icrc-accounts.modal.ts
  frontend/src/lib/utils/modals.utils.ts
  frontend/src/tests/lib/modals/accounts/IcrcTokenTransactionModal.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
  frontend/src/tests/page-objects/Accounts.page-object.ts
  frontend/src/tests/page-objects/IcrcTokenAccountsFooter.page-object.ts
  frontend/src/tests/page-objects/IcrcTokenTransactionModal.page-object.ts
Labels: Planned

#3898 GIX-2144: Load ckETH canisters on init public
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/lib/services/$public/app.services.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/lib/services/_public/app.services.spec.ts
  frontend/src/tests/utils/cketh.test-utils.ts
Labels: Planned

#3891 feat: review load Icrc accounts and extract common Icrc accounts page
  frontend/src/lib/components/accounts/IcrcAccountsPage.svelte
  frontend/src/lib/pages/CkBTCAccounts.svelte
  frontend/src/lib/pages/IcrcTokenAccounts.svelte
  frontend/src/lib/routes/Accounts.svelte
  frontend/src/lib/services/icrc-accounts.services.ts
  frontend/src/tests/lib/pages/IcrcTokenAccounts.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
Labels: feature request

#3904 GIX-2122: Send from Wallet
  frontend/src/lib/components/accounts/IcrcTokenWalletFooter.svelte
  frontend/src/lib/modals/accounts/IcrcTokenAccountsModals.svelte
  frontend/src/lib/pages/IcrcWallet.svelte
  frontend/src/lib/routes/Wallet.svelte
  frontend/src/lib/types/icrc-accounts.modal.ts
  frontend/src/tests/lib/routes/Wallet.spec.ts
  frontend/src/tests/page-objects/Wallet.page-object.ts
Labels: Planned

#3919 GIX-2152: ckETH not selected in governance
  frontend/src/lib/derived/selected-universe.derived.ts
  frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
Labels: Planned

#3920 GIX-2152: Non Selectable ICRC Tokens in Governance page
  frontend/src/lib/derived/selectable-universes.derived.ts
  frontend/src/tests/lib/derived/selectable-universes.derived.spec.ts
  frontend/src/tests/utils/cketh.test-utils.ts
  frontend/vitest.setup.ts
Labels: Planned

#3915 GIX-2151: Reload after transaction
  frontend/src/lib/components/accounts/IcrcTokenWalletFooter.svelte
  frontend/src/lib/modals/accounts/IcrcTokenAccountsModals.svelte
  frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte
  frontend/src/lib/pages/IcrcWallet.svelte
  frontend/src/lib/services/icrc-accounts.services.ts
  frontend/src/lib/types/icrc-accounts.modal.ts
  frontend/src/tests/lib/routes/Wallet.spec.ts
  frontend/src/tests/page-objects/Wallet.page-object.ts
Labels: Planned

#3922 Chore: Enable CkETH for tests
  frontend/vitest.setup.ts
Labels: Planned

#3926 GIX-2154: Support decimals numberToE8s
  frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte
  frontend/src/lib/services/icrc-accounts.services.ts
  frontend/src/lib/utils/token.utils.ts
  frontend/src/tests/lib/utils/token.utils.spec.ts
  frontend/src/tests/mocks/cketh-accounts.mock.ts
Labels: Unplanned
