Repository dfinity/nns-dapp, pull requests merged in 2023-02, with the labels that each got.

#1941 GIX-1340: Retry get open ticket
  frontend/src/lib/api/canisters.api.ts
  frontend/src/lib/components/project-detail/ParticipateButton.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
  frontend/src/lib/services/sns-sale.services.ts
  frontend/src/lib/stores/sns-tickets.store.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/utils/sns.utils.ts
  frontend/src/lib/utils/utils.ts
  frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
  frontend/src/tests/lib/services/sns-sale.services.spec.ts
  frontend/src/tests/lib/stores/sns-ticket.store.spec.ts
  frontend/src/tests/lib/utils/sns.utils.spec.ts
Labels: feature request

#1938 GIX-1331: Manage TxTooOld error in Participation flow
  frontend/package-lock.json
  frontend/src/lib/api/sns-aggregator.api.ts
  frontend/src/lib/api/sns-sale.api.ts
  frontend/src/lib/i18n/en.json
  frontend/src/lib/services/sns-sale.services.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/utils/sns.utils.ts
  frontend/src/tests/lib/api/sns-sale.api.spec.ts
  frontend/src/tests/lib/services/sns-sale.services.spec.ts
  frontend/src/tests/lib/utils/sns.utils.spec.ts
  frontend/src/tests/mocks/sns-aggregator.mock.ts
  frontend/src/tests/mocks/sns-projects.mock.ts
  frontend/src/tests/mocks/sns-response.mock.ts
Labels: feature request

#1953 feat: use TVL canister
  frontend/jest-setup.ts
  frontend/src/lib/api/tvl.api.cjs.ts
  frontend/src/lib/canisters/tvl/tvl.canister.ts
  frontend/src/lib/canisters/tvl/tvl.canister.types.ts
  frontend/src/lib/canisters/tvl/tvl.certified.idl.d.ts
  frontend/src/lib/canisters/tvl/tvl.certified.idl.js
  frontend/src/lib/canisters/tvl/tvl.did
  frontend/src/lib/canisters/tvl/tvl.idl.d.ts
  frontend/src/lib/canisters/tvl/tvl.idl.js
  frontend/src/lib/canisters/tvl/tvl.types.ts
  frontend/src/lib/components/metrics/TotalValueLocked.svelte
  frontend/src/lib/constants/canister-ids.constants.ts
  frontend/src/lib/constants/environment.constants.ts
  frontend/src/lib/constants/metrics.constants.ts
  frontend/src/lib/rest/binance.rest.ts
  frontend/src/lib/rest/governance-metrics.rest.ts
  frontend/src/lib/services/$public/governance-metrics.services.ts
  frontend/src/lib/services/$public/tvl.service.ts
  frontend/src/lib/types/metrics.ts
  frontend/src/lib/workers/metrics.worker.ts
  frontend/src/tests/lib/api/tvl.api.spec.ts
  frontend/src/tests/lib/components/metrics/TotalValueLocked.spec.ts
  frontend/src/tests/lib/rest/binance.rest.spec.ts
  frontend/src/tests/lib/rest/governance-metrics.rest.spec.ts
  frontend/src/tests/lib/services/_public/governance-metrics.services.spec.ts
  frontend/src/tests/lib/services/_public/tvl.services.spec.ts
Labels: feature request

#1967 Chore: Bump chromedriver to 109
  e2e-tests/package-lock.json
  e2e-tests/package.json
Labels: build

#1972 feat: restart participation in sale progress
  frontend/src/lib/components/project-detail/ParticipateButton.svelte
  frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
  frontend/src/lib/modals/sns/sale/SaleInProgressModal.svelte
  frontend/src/lib/services/sns-sale.services.ts
  frontend/src/lib/types/sale.ts
  frontend/src/lib/utils/sns.utils.ts
  frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
  frontend/src/tests/lib/api/sns-sale.api.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
  frontend/src/tests/lib/components/accounts/SelectNetworkDropdown.spec.ts
  frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
  frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts
  frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
  frontend/src/tests/lib/modals/sns/SaleInProgressModal.spec.ts
  frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
  frontend/src/tests/lib/services/sns-neurons.services.spec.ts
  frontend/src/tests/lib/services/sns-sale.services.spec.ts
  frontend/src/tests/lib/utils/date.utils.spec.ts
  frontend/src/tests/lib/utils/sns.utils.spec.ts
  frontend/src/tests/utils/transaction-modal.test.utils.ts
Labels: feature request

#1976 feat: nns.ic0.app is (still) main url of NNS-dapp
  frontend/src/app.html
  frontend/static/robots.txt
  frontend/static/sitemap.xml
Labels: feature request

#1963 feat: participation sale progress
  frontend/package-lock.json
  frontend/src/lib/components/project-detail/ParticipateButton.svelte
  frontend/src/lib/components/sale/AdditionalInfoForm.svelte
  frontend/src/lib/components/sale/AdditionalInfoReview.svelte
  frontend/src/lib/components/sale/SaleInProgress.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
  frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
  frontend/src/lib/modals/sns/sale/SaleInProgressModal.svelte
  frontend/src/lib/services/sns-sale.services.ts
  frontend/src/lib/stores/sns-tickets.store.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/types/sale.ts
  frontend/src/lib/utils/sns.utils.ts
  frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
  frontend/src/tests/lib/api/sns-sale.api.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
  frontend/src/tests/lib/components/accounts/SelectNetworkDropdown.spec.ts
  frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
  frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts
  frontend/src/tests/lib/components/sale/SaleInProgress.spec.ts
  frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.spec.ts
  frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts
  frontend/src/tests/lib/modals/accounts/TransactionModalTest.svelte
  frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
  frontend/src/tests/lib/modals/sns/SaleInProgressModal.spec.ts
  frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
  frontend/src/tests/lib/services/sns-neurons.services.spec.ts
  frontend/src/tests/lib/services/sns-sale.services.spec.ts
  frontend/src/tests/lib/utils/date.utils.spec.ts
  frontend/src/tests/lib/utils/sns.utils.spec.ts
  frontend/src/tests/utils/transaction-modal.test.utils.ts
Labels: feature request

#1975 fix: voting UI and cache
  frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectContainer.svelte
  frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.svelte
  frontend/src/lib/services/vote-registration.services.ts
  frontend/static/assets/libs/dummy-proposals.utils.js
Labels: bug

#1981 feat: display sale canister loading a bit more in a user friendly way
  frontend/src/lib/components/project-detail/ParticipateButton.svelte
  frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
  frontend/src/lib/components/ui/SpinnerText.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
Labels: feature request
