Repository dfinity/nns-dapp, pull requests merged in 2023-06, with the labels that each got.

#2629 Update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  frontend/package-lock.json
  frontend/package.json
Labels: release

#2637 Fix duplicate form field id in the same form
  e2e-tests/components/accounts-tab.ts
  e2e-tests/components/neurons-tab.ts
  frontend/package-lock.json
  frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts
  frontend/src/tests/lib/modals/accounts/IcpTransactionModal.spec.ts
  frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
  frontend/src/tests/utils/toggle.test-utils.ts
Labels: bug

#2631 fix: update the ic-admin download link
  scripts/setup
Labels: bug

#2645 Apple install to home screen look and feel
  frontend/src/app.html
  frontend/static/assets/favicons/apple-touch-icon.png
Labels: bug

#2646 Call ckBTC update balance in withdrawal account process
  frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte
  frontend/src/lib/services/ckbtc-minter.services.ts
  frontend/src/tests/lib/components/accounts/CkBTCWalletActions.spec.ts
  frontend/src/tests/lib/components/accounts/CkBTCWithdrawalAccount.spec.ts
  frontend/src/tests/lib/pages/CkBTCAccounts.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
Labels: feature request

#2658 Display "Select NNS" instead of "Select Token" on proposals
  frontend/src/lib/derived/title-token-selector.derived.ts
  frontend/src/tests/lib/derived/title-token-selector.derived.spec.ts
  frontend/src/tests/lib/modals/universe/SelectUniverseModal.spec.ts
Labels: feature request

#2661 Maskable icons
  frontend/static/assets/favicons/apple-touch-icon.png
  frontend/static/assets/favicons/icon-16x16.png
  frontend/static/assets/favicons/icon-192x192.png
  frontend/static/assets/favicons/icon-32x32.png
  frontend/static/assets/favicons/icon-512x512.png
Labels: bug

#2659 Sns invert Sns proposals filter for consistency
  frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
Labels: feature request

#2655 Update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  frontend/package-lock.json
  frontend/package.json
Labels: release

#2663 Fix Sns proposal reload with correct ID but NNS as universe
  frontend/src/lib/pages/SnsProposalDetail.svelte
  frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
Labels: bug

#2664 Fix Sns proposal lazy loading
  frontend/src/lib/pages/SnsProposals.svelte
Labels: bug

#2676 ckBTC get minter info api, services and stores
  frontend/package-lock.json
  frontend/src/lib/api/ckbtc-minter.api.ts
  frontend/src/lib/i18n/en.json
  frontend/src/lib/services/ckbtc-info.services.ts
  frontend/src/lib/stores/ckbtc-info.store.ts
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
  frontend/src/tests/lib/services/ckbtc-info.services.spec.ts
  frontend/src/tests/lib/stores/ckbtc-info.store.spec.ts
  frontend/src/tests/mocks/ckbtc-minter.mock.ts
Labels: feature request

#2672 Fix some setup issues on a new M1 installation
  HACKING.md
  e2e-tests/scripts/nns-canister-download
  scripts/setup
Labels: build

#2682 Load ckBTC info
  frontend/src/lib/pages/CkBTCAccounts.svelte
  frontend/src/lib/pages/CkBTCWallet.svelte
  frontend/src/lib/services/ckbtc-info.services.ts
  frontend/src/tests/lib/pages/CkBTCAccounts.spec.ts
  frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
  frontend/src/tests/lib/routes/Accounts.spec.ts
  frontend/src/tests/lib/routes/Wallet.spec.ts
  frontend/src/tests/lib/services/ckbtc-info.services.spec.ts
Labels: feature request

#2687 Use ckBTC info to display the number of confirmations
  frontend/src/lib/components/accounts/BitcoinAddress.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/tests/lib/components/accounts/BitcoinAddress.spec.ts
Labels: feature request

#2681 Use ckBTC info for retrieve min amount
  frontend/src/lib/constants/bitcoin.constants.ts
  frontend/src/lib/i18n/en.json
  frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
  frontend/src/lib/types/i18n.d.ts
  frontend/src/lib/utils/ckbtc.utils.ts
  frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
  frontend/src/tests/lib/utils/ckbtc.utils.spec.ts
  scripts/ckbtc/deploy-ckbtc
Labels: feature request

#2721 Icrc balance and transactions api for workers
  frontend/src/lib/worker-api/icrc-index.worker-api.ts
  frontend/src/lib/worker-api/icrc-ledger.worker-api.ts
  frontend/src/tests/lib/worker-api/icrc-index.worker-api.spec.ts
  frontend/src/tests/lib/worker-api/icrc-ledger.worker-api.spec.ts
Labels: feature request

#2719 Utils to extend JSON stringify and parse
  frontend/src/lib/stores/writable-stored.ts
  frontend/src/lib/utils/json.utils.ts
  frontend/src/tests/lib/utils/json.utils.spec.ts
Labels: feature request

#2695 TVL in various currencies
  frontend/src/lib/canisters/tvl/tvl.canister.ts
  frontend/src/lib/canisters/tvl/tvl.canister.types.ts
  frontend/src/lib/canisters/tvl/tvl.certified.idl.js
  frontend/src/lib/canisters/tvl/tvl.did
  frontend/src/lib/canisters/tvl/tvl.idl.js
  frontend/src/lib/canisters/tvl/tvl.types.ts
  frontend/src/lib/components/metrics/TotalValueLocked.svelte
  frontend/src/lib/types/metrics.ts
  frontend/src/lib/worker-api/tvl.worker-api.ts
  frontend/src/lib/worker-services/$public/tvl.worker-services.ts
  frontend/src/lib/workers/metrics.worker.ts
  frontend/src/tests/lib/canisters/tvl.canister.spec.ts
  frontend/src/tests/lib/components/metrics/TotalValueLocked.spec.ts
Labels: feature request

#2731 Collect all Icrc transactions for web workers
  frontend/src/lib/types/icrc.ts
  frontend/src/lib/types/post-message.transactions.ts
  frontend/src/lib/worker-services/icrc-transactions.worker-services.ts
  frontend/src/lib/worker-types/transactions.worker-types.ts
  frontend/src/tests/lib/worker-services/icrc-transactions.worker-services.spec.ts
Labels: feature request

#2733 Animate new transaction being pushed in the list
  frontend/src/lib/components/accounts/IcrcTransactionsList.svelte
  frontend/src/lib/components/accounts/TransactionCard.svelte
  frontend/src/lib/components/accounts/TransactionList.svelte
Labels: feature request

#2755 Transactions worker
  frontend/src/lib/constants/accounts.constants.ts
  frontend/src/lib/services/worker-transactions.services.ts
  frontend/src/lib/stores/icrc-transactions.store.ts
  frontend/src/lib/types/post-messages.ts
  frontend/src/lib/workers/transactions.worker.ts
  frontend/src/tests/lib/services/worker-transactions.services.spec.ts
Labels: feature request

#2756 Balances worker
  frontend/src/lib/services/worker-balances.services.ts
  frontend/src/lib/types/post-message.balances.ts
  frontend/src/lib/types/post-messages.ts
  frontend/src/lib/worker-services/icrc-balances.worker-services.ts
  frontend/src/lib/workers/balances.worker.ts
  frontend/src/tests/lib/services/worker-balances.services.spec.ts
  frontend/src/tests/lib/worker-services/icrc-balances.worker-services.spec.ts
Labels: feature request

#2759 Balances and transactions worker observer
  frontend/src/lib/components/accounts/IcrcBalancesObserver.svelte
  frontend/src/lib/components/accounts/IcrcTransactionsObserver.svelte
  frontend/src/lib/types/icrc.observer.ts
  frontend/src/tests/lib/components/accounts/IcrcBalancesObserver.spec.ts
  frontend/src/tests/lib/components/accounts/IcrcTransactionsObserver.spec.ts
Labels: feature request

#2764 Sync indicator
  frontend/package-lock.json
  frontend/src/lib/components/header/AccountMenu.svelte
  frontend/src/lib/components/header/AccountSyncIndicator.svelte
  frontend/src/lib/components/header/HeaderToolbar.svelte
  frontend/src/lib/components/layout/Content.svelte
  frontend/src/lib/components/layout/UniverseSplitContent.svelte
  frontend/src/lib/i18n/en.json
  frontend/src/lib/types/i18n.d.ts
  frontend/src/tests/lib/components/header/AccountSyncIndicator.spec.ts
Labels: feature request

#2769 Refresh accounts balance periodically on Sns wallet
  frontend/src/lib/components/accounts/SnsWalletBalancesObserver.svelte
  frontend/src/lib/pages/SnsWallet.svelte
  frontend/src/lib/services/worker-balances.services.ts
  frontend/src/lib/stores/sns-accounts.store.ts
  frontend/src/tests/lib/components/accounts/IcrcBalancesObserver.spec.ts
  frontend/src/tests/lib/components/accounts/SnsWalletBalancesObserver.spec.ts
  frontend/src/tests/lib/components/accounts/SnsWalletBalancesObserverTest.svelte
  frontend/src/tests/lib/pages/SnsWallet.spec.ts
  frontend/src/tests/lib/stores/sns-accounts.store.spec.ts
  frontend/src/tests/mocks/post-message.mocks.ts
Labels: feature request

#2773 feat: icrc-accounts.store update
  frontend/src/lib/stores/icrc-accounts.store.ts
  frontend/src/tests/lib/stores/icrc-accounts.store.spec.ts
Labels: feature request

#2779 docs: release notes web worker, cronjob and payment
  CHANGELOG-Nns-Dapp.md
Labels: documentation

#2784 Auto close sync indicator
  frontend/src/lib/components/header/AccountSyncIndicator.svelte
  frontend/src/tests/lib/components/header/AccountSyncIndicator.spec.ts
Labels: feature request

#2786 Fix header button and modal ui quirks
  frontend/package-lock.json
Labels: style

#2776 docs: review README
  BUILD.md
  README.md
Labels: documentation

#2788 Ignore sign-in "error" UserInterrupt
  CHANGELOG-Nns-Dapp.md
  frontend/src/lib/components/common/SignIn.svelte
  frontend/src/lib/components/header/LoginIconOnly.svelte
  frontend/src/lib/services/auth.services.ts
  frontend/src/tests/lib/services/auth.services.spec.ts
Labels: feature request
